name: "Semantic release"

on:
  push:
    branches:
      - main

jobs:
  release:
    # do not run semantic release on forks
    if: ${{ github.repository == 'shirte/impynb' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    concurrency: release
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.11.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}